name: test-action

on: push 
 
jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Chrome
        run: |
            sudo apt-get update
